### ISSUE TITLE
find datasource for concerts across cities

### ISSUE THREAD

**Issue by hannesdatta** [course-dprep/team-assignment-team2#2]
__Deliverable:__
- likely a website or dataset that list city names along with dates/months/years and the number of concerts
-

**Comment by karanlalchandani** [comment]
This is what I found for concert data so far. The more popular concert venues and also based on cities that are available in InsideAirbnb: 

- Amsterdam - Ziggo Dome: https://www.ziggodome.nl/agenda/archief 
- London - O2 Arena: https://en.wikipedia.org/wiki/List_of_entertainment_events_at_the_O2_Arena 
- London - Wembley Stadium: https://www.uktw.co.uk/archive/greater-london/outer-london/wembley/V359/ 
- Paris - Paris La Défense Arena: https://en.wikipedia.org/wiki/Paris_La_D%C3%A9fense_Arena  
- Sydney - Qudos Bank Arena: https://en.wikipedia.org/wiki/List_of_entertainment_events_at_the_Sydney_SuperDome  
- Manchester - AO Arena (formerly Manchester Arena): https://www.uktw.co.uk/archive/V209071540/ 
- New York - Madison Square Garden: https://en.wikipedia.org/wiki/List_of_entertainment_events_at_Madison_Square_Garden 
- Los Angeles - Crypto.com Arena (formerly Staples Center): https://en.wikipedia.org/wiki/List_of_entertainment_events_at_Crypto.com_Arena

**Comment by karanlalchandani** [comment]
The focus of our study has changed, so this issue is no longer relevant and can be closed
