### ISSUE TITLE
explore alternative RQs

### ISSUE THREAD

**Issue by hannesdatta** [course-dprep/team-assignment-team2#3]
We already have worked on #1, but just for the fun of it, let's try to think about alternative questions and make up our mind later.

__Deliverable:__
- bullet-point style list with potential RQs that can be pitched to the team by whoever works on this issue

**Comment by Yufan-99** [comment]
In case there isn't available dataset of concert, here are extra RQs we could explore:

- How does Airbnb house density in the neighbourhood,  annual reviews amount of the listings, property_type relate to the price, and how does the relationship between  neighbourhood Airbnb density and prices depend on cities.
- Does the host characteristic plays a role in pricing, including host response time, host response rate, whether it is host identity verified and super host.
