### ISSUE TITLE
define for which cities to do the analysis

### ISSUE THREAD

**Issue by hannesdatta** [course-dprep/team-assignment-team2#5]

**Comment by BastiaanVanHouten** [comment]
I would either decide on cities in Europe or the US. From here we can distinguish what we see as a 'large event'(possibly based on the attendence of the event) .  (Events could be sports, music  based but also big happenings) So I would advise on splitting the cities up. Everyone looks up their cities and sees which events has an attendence over the cut off. If the city does not have such an event we should exclude it from out database. If too much cities do not have an event making the cut off we should possibly lower the cutoff.  From their we can see the elasticity of the prices based on the events.

**Comment by BastiaanVanHouten** [comment]
https://www.28degreescard.com.au/travel-inspiration/10-largest-music-festivals-around-the-globe.html

https://www.genfare.com/resources/largest-events-state/

**Comment by BastiaanVanHouten** [comment]
[Webscraping cheatsheet.pptx](https://github.com/course-dprep/team-assignment-team2/files/10804378/Webscraping.cheatsheet.pptx)
