### ISSUE TITLE
ODCM - Section 2 deliverable

### ISSUE THREAD

**Issue by edinescu** [course-dprep/team-assignment-team2#7]
Explain how you addressed challenges #1.1-#1.2, leading to your selected data source [About 10 sources + explanation of max. 250 words]

- https://www.sitejabber.com/reviews/hellofresh.com

- https://www.facebook.com/HelloFreshSverige/reviews

- https://github.com/hpufo/HelloFresh/blob/master/USE_THE_API.md

**Comment by karanlalchandani** [comment]
Added to the document created by Yufan in the google drive folder
